import type { NextPage } from 'next'
import type { GetPoll } from 'types/getPoll'
import styles from 'styles/Home.module.scss'
import Head from 'next/head'
import { useRouter } from 'next/router'
import CreatePollForm from 'components/createPollForm'
//@ts-ignore
import getBrowserFingerprint from 'get-browser-fingerprint';


const Home: NextPage = () => {

  const router = useRouter();

  const createPoll = async (e: React.FormEvent<HTMLElement>) => {
    e.preventDefault();

    const form = e.target as typeof e.target & {
      title: { value: string };
      description: { value: string };
      duration: { value: string };
    };

    const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASEURL}/createPoll`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: form.title.value,
        description: form.description.value,
        fingerprint: String(getBrowserFingerprint()),
        duration: form.duration.value,
      })
    });

    const res: GetPoll = await response.json();
    console.log(res);

    if (res.Type == "failure") {
      alert(res.Error);
      return
    }

    if (res.Type == "success") {
      router.push(`/poll/${res.Data.idt}#${res.Data.edit}`);
      return
    }
  }

  return (
    <>
      <Head>
        <title>Exam Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Exam Poll</h1>
        <CreatePollForm onSubmit={createPoll} className={styles.form} />
      </main>
    </>
  )

}

export default Home
