import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

// NOTE: TEMP

const createPoll = async () => {
  const response = await fetch('http://localhost:3000/createPoll', {
    
  });
  console.log(response);
}


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exam Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Exam Poll</h1>
        <button onClick={() => createPoll()}>Create Poll</button>
      </main>
    </div>
  )
}

export default Home
