import type { NextPage } from 'next'
import styles from 'styles/Home.module.scss'
import Head from 'next/head'
import { useRouter } from 'next/router'


const Home: NextPage = () => {

  const router = useRouter();

  const createPoll = async (e: React.FormEvent<HTMLElement>) => {
    e.preventDefault();

    const form = e.target as typeof e.target & {
      title: { value: string };
      description: { value: string };
      duration: { value: string };
    };

    const response = await fetch('http://localhost:8000/createPoll', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: form.title.value,
        description: form.description.value,
        fingerprint: "some fingerprint",
        duration: form.duration.value,
      })
    });

    const res = await response.json();
    console.log(res);

    if (res.Type == "failure") {
      alert(res.Error);
      return
    }

    if (res.Type == "success") {
      router.push(`/poll/${res.Data.idt}`);
      return
    }
  }

  return (
    <>
      <Head>
        <title>Exam Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Exam Poll</h1>

        <form onSubmit={createPoll} className={styles.form}>
          <label htmlFor="poll_title">Title</label>
          <input type="text" id="poll_title" name="title"/>

          <label htmlFor="poll_description">Description</label>
          <input type="text" id="poll_description" name="description"/>

          <label htmlFor="poll_duration">Duration</label>
          <select id="poll_duration" name="duration" defaultValue="1d">
            <option value="4h">4h</option>
            <option value="8h">8h</option>
            <option value="12h">12h</option>
            <option value="1d">1d</option>
            <option value="2d">2d</option>
            <option value="4d">4d</option>
            <option value="7d">7d</option>
          </select>

          <button type="submit">Create Poll</button>
        </form>
      </main>
    </>
  )

}

export default Home
