import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Poll.module.scss'

const Poll: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exam Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Poll</h1>
      </main>
    </div>
  )
}

export default Poll
